apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkeactrgy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jkeactrgy
  template:
    metadata:
      labels:
        app: jkeactrgy
    spec:
      containers:
      - image: okteto.dev/jkeactrgy:latest
        name: jkeactrgy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.moviecrumbs.net"
        - name: Vless_UUID
          value: "4c4d647e-4dac-485c-92d1-e1b249241466"
        - name: Vless_Path
          value: "/FAEL05D"
        - name: Vmess_UUID
          value: "4c4d647e-4dac-485c-92d1-e1b249241466"
        - name: Vmess_Path
          value: "/CIOKT96"
        - name: Share_Path
          value: "/Share369"
