apiVersion: apps/v1
kind: Deployment
metadata:
  name: uioervchza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uioervchza
  template:
    metadata:
      labels:
        app: uioervchza
    spec:
      containers:
      - image: okteto.dev/uioervchza:latest
        name: uioervchza
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "moviemora.com"
        - name: Vless_UUID
          value: "ec24ffc7-4feb-4d97-9677-c9b9fd0e55f2"
        - name: Vless_Path
          value: "/Gsdfsdui"
        - name: Vmess_UUID
          value: "ec24ffc7-4feb-4d97-9677-c9b9fd0e55f2"
        - name: Vmess_Path
          value: "/kioedhv"
        - name: Share_Path
          value: "/Share054"
