apiVersion: apps/v1
kind: Deployment
metadata:
  name: violiert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: violiert
  template:
    metadata:
      labels:
        app: violiert
    spec:
      containers:
      - image: okteto.dev/violiert:latest
        name: violiert
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www4.watchserieshd.tv"
        - name: Vless_UUID
          value: "22dc5350-2031-4c39-93d9-099767500a1d"
        - name: Vless_Path
          value: "/LKAS34YX"
        - name: Vmess_UUID
          value: "22dc5350-2031-4c39-93d9-099767500a1d"
        - name: Vmess_Path
          value: "/rejxcmla"
        - name: Share_Path
          value: "/Share214"
