apiVersion: apps/v1
kind: Deployment
metadata:
  name: badertion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: badertion
  template:
    metadata:
      labels:
        app: badertion
    spec:
      containers:
      - image: okteto.dev/badertion:latest
        name: badertion
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.moviecrumbs.net"
        - name: Vless_UUID
          value: "0db2e44c-3e8e-41ea-a9fd-479c78058079"
        - name: Vless_Path
          value: "/r5hcvoit"
        - name: Vmess_UUID
          value: "0db2e44c-3e8e-41ea-a9fd-479c78058079"
        - name: Vmess_Path
          value: "/ydf2ghxc"
        - name: Share_Path
          value: "/Share721"
