apiVersion: apps/v1
kind: Deployment
metadata:
  name: heandr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heandr
  template:
    metadata:
      labels:
        app: heandr
    spec:
      containers:
      - image: okteto.dev/heandr:latest
        name: heandr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "kissanime.ru.net"
        - name: Vless_UUID
          value: "5aa889fc-2f3d-4879-922a-6659b712d105"
        - name: Vless_Path
          value: "/BYfkj0rf"
        - name: Vmess_UUID
          value: "5aa889fc-2f3d-4879-922a-6659b712d105"
        - name: Vmess_Path
          value: "/sdiu64i4rt"
        - name: Share_Path
          value: "/Share501"
